#:schema node_modules/wrangler/config-schema.json
name = "blazzing-app"
pages_build_output_dir = "./build/client"
compatibility_flags = [ "nodejs_compat_v2" ]

[placement]
mode = "smart"

[vars]
WORKER_URL = 'http://localhost:8787'
REPLICACHE_KEY='l024b847d70a04f84b3768c6d1d1db25f'
HONEYPOT_SECRET = '9ad47a935f51db545823d436ae31642c40a48f7a6490dff38ec166f45ffc3aa1'
PARTYKIT_HOST='blazzing-app.lordpachimari.partykit.dev'
ENVIRONMENT = 'development'
SESSION_SECRET = '38e433dbfd9491cdfe841d7169b5de37a7947718df325ba3396f87667becc927'
STRIPE_PUBLISHABLE_KEY= 'pk_test_51PoTQ6GCry79OvxeohPUazRmNXKKvqDg3dgHMGnvLx2jK5BPICAzunve4VtcItpLDBLX4r2weFErJ0w5qu8EwVJz008UhMhvq1'
[[kv_namespaces]]
binding = "KV"
id = "7cf103d6bdae4b43bace2c0051307639"


