name = "blazzing-worker"
compatibility_date = "2024-09-12"
compatibility_flags = [ "nodejs_compat_v2" ]

[vars]
LIVEKIT_SERVER_URL = 'wss://test-42h1qr2q.livekit.cloud'
LIVEKIT_API_KEY = 'APIs6VDf6iqcGgS'
LIVEKIT_SECRET_KEY = '8Ny4c2mvJGpLpZVI9sf0NoCEiMl59ZZC7eCoiZtffUED'

[env.development]
LIVEKIT_SERVER_URL = 'wss://test-42h1qr2q.livekit.cloud'
LIVEKIT_API_KEY = 'APIs6VDf6iqcGgS'
LIVEKIT_SECRET_KEY = '8Ny4c2mvJGpLpZVI9sf0NoCEiMl59ZZC7eCoiZtffUED'

